apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vm-host-daemon-monitor
  namespace: default
  labels:
    release: prometheus #must
spec:
  selector:
    matchLabels:
      app: ebpf-host-exporter #must to select the service(external-target service)
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 5s
